### ISSUE TITLE
Failed to install ai-translation in Mac

### ISSUE THREAD

**Issue by longdafeng** [ossrs/ai-translation#1]
Chip: Apple M2 Max
OS: 13.4.1 (22F82)

```
(venv) longda@LongdaMac ai-translation % pip install -r requirements.txt
Collecting transformers@ git+https://github.com/huggingface/transformers.git@5f3efdf762a5de89d354879d3d6bed689bbc73b7 (from -r requirements.txt (line 32))
  Cloning https://github.com/huggingface/transformers.git (to revision 5f3efdf762a5de89d354879d3d6bed689bbc73b7) to /private/var/folders/ws/c1wqr21s3r5dt9_j21_l33br0000gn/T/pip-install-79o1ao2y/transformers_ae5be64f8e164ee19a70f882843d63f8
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /private/var/folders/ws/c1wqr21s3r5dt9_j21_l33br0000gn/T/pip-install-79o1ao2y/transformers_ae5be64f8e164ee19a70f882843d63f8
  Running command git rev-parse -q --verify 'sha^5f3efdf762a5de89d354879d3d6bed689bbc73b7'
  Running command git fetch -q https://github.com/huggingface/transformers.git 5f3efdf762a5de89d354879d3d6bed689bbc73b7
  Running command git checkout -q 5f3efdf762a5de89d354879d3d6bed689bbc73b7
  Resolved https://github.com/huggingface/transformers.git to commit 5f3efdf762a5de89d354879d3d6bed689bbc73b7
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp==3.8.4 (from -r requirements.txt (line 1))
  Using cached aiohttp-3.8.4-cp311-cp311-macosx_11_0_arm64.whl (332 kB)
Collecting aiosignal==1.3.1 (from -r requirements.txt (line 2))
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout==4.0.2 (from -r requirements.txt (line 3))
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting attrs==23.1.0 (from -r requirements.txt (line 4))
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting certifi==2023.5.7 (from -r requirements.txt (line 5))
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting charset-normalizer==3.1.0 (from -r requirements.txt (line 6))
  Using cached charset_normalizer-3.1.0-cp311-cp311-macosx_11_0_arm64.whl (121 kB)
Collecting filelock==3.12.2 (from -r requirements.txt (line 7))
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting frozenlist==1.3.3 (from -r requirements.txt (line 8))
  Using cached frozenlist-1.3.3-cp311-cp311-macosx_11_0_arm64.whl (34 kB)
Collecting fsspec==2023.6.0 (from -r requirements.txt (line 9))
  Using cached fsspec-2023.6.0-py3-none-any.whl (163 kB)
Collecting huggingface-hub==0.15.1 (from -r requirements.txt (line 10))
  Using cached huggingface_hub-0.15.1-py3-none-any.whl (236 kB)
Collecting idna==3.4 (from -r requirements.txt (line 11))
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting Jinja2==3.1.2 (from -r requirements.txt (line 12))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting llvmlite==0.40.1 (from -r requirements.txt (line 13))
  Downloading llvmlite-0.40.1-cp311-cp311-macosx_11_0_arm64.whl (28.1 MB)
     ━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/28.1 MB 17.1 kB/s eta 0:22:37
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 466, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 587, in _prepare_linked_requirement
    local_file = unpack_url(
                 ^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
           ^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/longda/work/repo/ai/ai-translation/venv/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

**Comment by longdafeng** [comment]
is it due to network error? 
is it due to failed to fetch package from abroad?

**Comment by winlinvip** [comment]
Network issue.
